test: &default

  # Credentials for REST APIs
  client_id: ARW0AxBp930OdIxPtLwzMYUr9Oz4zz7DbkIOLTAVKu0h09IoePqEG7i52A04
  client_secret: EGC8aBDAlcGlrJSixUY96j0vGoSwSrbq_HrjalHYHXS2fa7dDa1nilhy6kLT

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
